name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      # - name: Compile protobuf
      #   run: npm run compile-proto
      #   working-directory: ./

      - name: Build project
        run: npm run build
        working-directory: ./

      - name: Lint project
        run: npm run lint
